#Server config
server.port=8080

# Application Name
spring.application.name=degworks-and-bs-backend

#Logging
logging.level.degworks-and-bs-backend=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# H2 Config
spring.datasource.url=jdbc:h2:mem:dwbsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA Configuration (for future use)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false


