# ===============================
# Server config
# ===============================
server.port=8080
spring.application.name=degworks-and-bs-backend

# ===============================
# Logging
# ===============================
logging.level.root=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# ===============================
# H2 File Datasource
# ===============================
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=America/New_York
# ===============================
# H2 Console (browser UI)
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console